# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WatchflareAgent < Formula
  desc "Watchflare server monitoring agent"
  homepage "https://watchflare.io"
  version "0.29.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.29.0/watchflare-agent_0.29.0_darwin_amd64.tar.gz"
      sha256 "cd5d5188350c80851ecbb852d82ee7dc25c19c39339c29522cd6496eac74b56a"

      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.29.0/watchflare-agent_0.29.0_darwin_arm64.tar.gz"
      sha256 "a3b2ce79b6ad2399afce0f446e3e8115cc8bad606f9d758e581fb1ce623dcb97"

      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.29.0/watchflare-agent_0.29.0_linux_amd64.tar.gz"
      sha256 "d1b01783d46d6cad1c5069e2bd8bd8b17b32fe3f190b24966dad4d91b0e8a35b"
      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.29.0/watchflare-agent_0.29.0_linux_arm64.tar.gz"
      sha256 "345fdf225312f1af8450de560ccd37f68badf9b87ca189fe3515d6fae860d131"
      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
  end

  def caveats
    <<~EOS
      Register your agent before starting the service:
        watchflare-agent-launcher register --token=YOUR_TOKEN --host=YOUR_HOST

      Then start the service:
        brew services start watchflare-agent

      To update:
        brew upgrade watchflare-agent && brew services restart watchflare-agent
    EOS
  end

  service do
    run ["#{bin}/watchflare-agent-launcher"]
    log_path "#{var}/log/watchflare-agent.log"
    error_log_path "#{var}/log/watchflare-agent.log"
    keep_alive true
    restart_delay 5
    process_type :background
  end
end
