# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WatchflareAgent < Formula
  desc "Watchflare host monitoring agent"
  homepage "https://watchflare.io"
  version "0.31.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.31.0/watchflare-agent_0.31.0_darwin_amd64.tar.gz"
      sha256 "e8bbb41d5c96f598b5b8bc79037d08c44e0f8b59d52035dd53ea7da3ee8aff5d"

      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.31.0/watchflare-agent_0.31.0_darwin_arm64.tar.gz"
      sha256 "01178f75db69bdc29da0e34ed2f83aa46d3e4e14ec0e53645a76af3bd5d0278e"

      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.31.0/watchflare-agent_0.31.0_linux_amd64.tar.gz"
      sha256 "9d3fb628a0a2e03a100a50f40eaf9206a983a6a0d20bde0954ace2df8c2dd56a"
      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.31.0/watchflare-agent_0.31.0_linux_arm64.tar.gz"
      sha256 "9069d04f07be037bf5fad9bcd4939cb6d8ba032da4dac920d7e6c86d2a434db8"
      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
  end

  def caveats
    <<~EOS
      Register your agent before starting the service:
        watchflare-agent-launcher register --token=YOUR_TOKEN --host=YOUR_HOST

      Then start the service:
        brew services start watchflare-agent

      To update:
        brew upgrade watchflare-agent && brew services restart watchflare-agent
    EOS
  end

  service do
    run ["#{bin}/watchflare-agent-launcher"]
    log_path "#{var}/log/watchflare-agent.log"
    error_log_path "#{var}/log/watchflare-agent.log"
    keep_alive true
    restart_delay 5
    process_type :background
  end
end
